name: MobBlock
main: com.github.r0306.MobBlock.MobBlock
version: 1.0.0
permissions:
    mb.*:
        description: Gives access to all MobBlock features.
        default: op
        children:
            mb.create: true
            md.toggle: true
            md.listen: true
    mb.create:
        description: Allows player to create a mob block.
        default: true
    mb.toggle:
        description: Allows player to change the sound of the mob block.
        default: true
    mb.listen:
        description: Allows player to hear sounds played from the mob block.
        default: true